### ISSUE TITLE
Question: why have different volumes for the caches?

### ISSUE THREAD

**Issue by jaapjansma** [michaelmcandrew/civicrm-buildkit-docker#23]
Each cache (e.g. git, drush, bower etc) gets mounted under /buildkit
But /buildkit it self is also a volume. So why have different volumes for each cache?

**Comment by michaelmcandrew** [comment]
hey @jaapjansma, good question :)

I can't remember the exact reasoning.  I think the general principle I was following was identify what NEEDS to be mounted as as volume and only mount that, leaving the rest to be read directly from the container. Why? Because 1) reading from the container is quicker, and 2) less caching is less to get out of sync when you update the container.

Given the above, I am not sure why I mounted /buildkit as well. Either it was a mistake, or something wasn't working without it.

**Comment by jaapjansma** [comment]
Buildkit contains some configurations of the sites created, those configurations need to be persisted after starting/stoping a container. So my assumption is that you did mount buildkit for this purpose.

**Comment by michaelmcandrew** [comment]
> Buildkit contains some configurations of the sites created

What config are you talking about in particular? The amp config is in this volume: https://github.com/michaelmcandrew/civicrm-buildkit-docker/blob/master/docker-compose.yml#L19. Off the top of my head, I can't think of any other config.

**Comment by jaapjansma** [comment]
I have removed the buildkit volume and kept the others and it all works quite well.

**Comment by michaelmcandrew** [comment]
same here :) worth merging in at some point...

**Comment by michaelmcandrew** [comment]
you know what, there are other files in /buildkit like `.bash_history` and `.mysql_history` that are useful to persist.

Given the amount of command line work that people typically do with buildkit (and the various misc. artefacts that might be produced as a result, I am less inclined to remove it.

**Comment by michaelmcandrew** [comment]
closing for now...
