### ISSUE TITLE
Switch to php 7.2

### ISSUE THREAD

**Issue by michaelmcandrew** [michaelmcandrew/civicrm-buildkit-docker#36]

**Comment by michaelmcandrew** [comment]
@wmortada - do you know where to find the recommended php version for civicrm?

**Comment by mattwire** [comment]
Here: https://docs.civicrm.org/sysadmin/en/latest/requirements/#php-version  PHP7.2 is the currently recommended version.

**Comment by michaelmcandrew** [comment]
ah, thanks @mattwire - I was looking in  https://docs.civicrm.org/dev - silly me :)

**Comment by wmortada** [comment]
I just did a naive test of this by updating the Dockerfile to `FROM php:7.2-apache`.  Unfortunately this doesn't work because mcrypt was removed from PHP7.2.  It looks like [mcrypt isn't required](https://civicrm.stackexchange.com/questions/25769/what-to-do-with-mcrypt-message-after-upgrading-to-php-7-2) for recent versions of CiviCRM so I guess the answer is to remove the relevant lines from the Dockerfile.

**Comment by michaelmcandrew** [comment]
@wmortada - you might want to look at https://github.com/michaelmcandrew/civicrm-buildkit-docker/tree/master/publish and the templates for creating Docker files that work with various versions of PHP, e.g. https://github.com/michaelmcandrew/civicrm-buildkit-docker/blob/3ec90aa6c506403b6415c6ae7c40d81951db4877/publish/templates/civicrm/Dockerfile.twig#L67-L72

**Comment by wmortada** [comment]
Ah, okay, I didn't realise you'd set this up as a template.

**Comment by michaelmcandrew** [comment]
we're now defaulting to php7.2 so closing
