### ISSUE TITLE
Error when creating dmaster demo site

### ISSUE THREAD

**Issue by MarcMichalsky** [michaelmcandrew/civicrm-buildkit-docker#72]
When I pull a fresh copy of this repository and execute `docker-compose exec -u buildkit civicrm civibuild create dmaster` the building process fails with the following error messages. The containers are all running.

```bash
Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                               [error]
The drush command 'site-install' could not be executed.                                                                                                                                                 [error]
```
I tested it on two different Ubuntu machines with the same result.

**Comment by michaelmcandrew** [comment]
Hi @MarcMichalsky 

I 'reset' my install with `docker-compose down -v;rm -r build;mkdir build;docker-compose pull;docker-compose up -d`.

I ran `docker-compose exec -u buildkit civicrm civibuild create dmaster`.

It completed OK for me.

I am guessing that there is some more useful diagnostic information if you scroll further up in your output. Feel free to check it yourself - it might give you a clue. Otherwise, happy to help more.

**Comment by MarcMichalsky** [comment]
Oh, okay, that worked. I was not aware that after pulling a new version of `civicrm-buildkit-docker` I had to remove all volumes, too. The `-v` flag did the trick. Thanks a lot!

**Comment by michaelmcandrew** [comment]
Great :)
